services:
  app:
    image: "***/enterprise-nodejs-service:latest"
    container_name: enterprise-nodejs-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    volumes:
      - ./database.sqlite:/app/database.sqlite
      - ./logs:/app/logs
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s